trigger:
- main

variables:
- group: CakeBuildLib

pool:
  vmImage: 'ubuntu-18.04'

steps:
 - task: UseDotNet@2
   inputs:
    version: '6.0.x'

 - task: DotNetCoreCLI@2
   displayName: 'Restore dotnet tools'
   inputs:
     command: 'custom'
     custom: 'tool'
     arguments: 'restore'

 - task: Docker@2
   displayName: Login to ACR
   inputs:
    command: login
    containerRegistry: cakebuildregistry

 - bash: |
    dotnet cake -dockerregistryname $(registryname) -sonarlogin $(sonarlogin)
   env:
    SONAR_PASSWORD: $(sonarpassword)