trigger:
- main

pool:
  vmImage: 'ubuntu-18.04'

steps:
 - task: DotNetCoreCLI@2
   displayName: 'Restore dotnet tools'
   inputs:
     command: 'custom'
     custom: 'tool'
     arguments: 'restore'

 - script: |
    dotnet cake